
import React, { useState } from 'react';
import { GoogleGenAI, GenerateImagesResponse } from '@google/genai';
import { Icon } from './Icon';
import { Spinner } from './Spinner';

export const ImageGenerator: React.FC = () => {
    const [prompt, setPrompt] = useState('');
    const [aspectRatio, setAspectRatio] = useState('1:1');
    const [generatedImage, setGeneratedImage] = useState<string | null>(null);
    const [isLoading, setIsLoading] = useState(false);
    const [error, setError] = useState<string | null>(null);

    const handleGenerate = async () => {
        if (!prompt.trim() || !process.env.API_KEY) {
            setError('Prompt cannot be empty and API key must be configured.');
            return;
        }
        setIsLoading(true);
        setError(null);
        setGeneratedImage(null);

        try {
            const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
            const response: GenerateImagesResponse = await ai.models.generateImages({
                model: 'imagen-4.0-generate-001',
                prompt: prompt,
                config: {
                    numberOfImages: 1,
                    outputMimeType: 'image/jpeg',
                    aspectRatio: aspectRatio as "1:1" | "3:4" | "4:3" | "9:16" | "16:9",
                },
            });

            const base64ImageBytes: string = response.generatedImages[0].image.imageBytes;
            const imageUrl = `data:image/jpeg;base64,${base64ImageBytes}`;
            setGeneratedImage(imageUrl);
        } catch (err) {
            console.error('Image generation error:', err);
            setError('Failed to generate image. Please check the console for details.');
        } finally {
            setIsLoading(false);
        }
    };

    return (
        <div className="h-full flex flex-col bg-gray-800 rounded-lg p-6 shadow-xl">
            <h1 className="text-2xl font-bold mb-4">Image Generation</h1>
            <p className="text-gray-400 mb-6">Create stunning visuals with Imagen. Describe what you want to see, and let Gemini bring it to life.</p>
            
            <div className="flex flex-col md:flex-row gap-4 mb-4">
                <input
                    type="text"
                    value={prompt}
                    onChange={(e) => setPrompt(e.target.value)}
                    placeholder="e.g., A cinematic shot of a raccoon detective in a rainy city"
                    className="flex-1 bg-gray-700 p-3 rounded-lg focus:outline-none focus:ring-2 focus:ring-purple-500"
                />
                <select 
                    value={aspectRatio} 
                    onChange={e => setAspectRatio(e.target.value)}
                    className="bg-gray-700 p-3 rounded-lg focus:outline-none focus:ring-2 focus:ring-purple-500"
                >
                    <option value="1:1">Square (1:1)</option>
                    <option value="16:9">Widescreen (16:9)</option>
                    <option value="9:16">Portrait (9:16)</option>
                    <option value="4:3">Landscape (4:3)</option>
                    <option value="3:4">Tall (3:4)</option>
                </select>
                <button
                    onClick={handleGenerate}
                    disabled={isLoading}
                    className="px-6 py-3 bg-purple-600 rounded-lg font-semibold hover:bg-purple-700 transition flex items-center justify-center gap-2 disabled:bg-gray-500"
                >
                    {isLoading ? <Spinner /> : <Icon icon="image-gen" className="h-5 w-5" />}
                    Generate
                </button>
            </div>

            {error && <p className="text-red-400 text-center my-4">{error}</p>}

            <div className="flex-1 bg-gray-900 rounded-lg flex items-center justify-center mt-4">
                {isLoading && (
                    <div className="text-center">
                        <Spinner size="h-12 w-12" />
                        <p className="mt-4 text-gray-400">Generating your masterpiece...</p>
                    </div>
                )}
                {generatedImage && !isLoading && (
                    <img src={generatedImage} alt="Generated by Gemini" className="max-h-full max-w-full object-contain rounded-lg p-2" />
                )}
                {!generatedImage && !isLoading && (
                    <div className="text-center text-gray-500">
                        <Icon icon="image" className="h-24 w-24 mx-auto mb-4" />
                        <p>Your generated image will appear here.</p>
                    </div>
                )}
            </div>
        </div>
    );
};
